In [ ]:
import pandas as pd
df = pd.read_csv("./clean_5.csv")
#df.info()
df=df.drop('Unnamed: 0.1',axis=1)           # drop s the column named  ' Unnamed 0.1' fromthe dataset.
x=df.iloc[:,df.columns != 'Label']          # selects all the rows in the dataframe including all the columns except column 'label'.
y=df.iloc[:,-1]                             #selects all the rows and columns except the last row 
print("x\n",x.info())
y = pd.DataFrame(y)
print('y\n',y.info())
df.describe()

In [2]:
#normalizating the data
#df.iloc[:,df.columns != ' Flow Packets/s' or df.columns != 'Flow Bytes/s']
normalized_df=(df-df.mean())/df.std()       #to-do
normalized_df=normalized_df.drop(' Flow Packets/s',axis=1)
normalized_df=normalized_df.drop('Flow Bytes/s',axis=1)

import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(100,200))
cor = normalized_df.corr()
sn.heatmap(cor, annot=True, cmap=plt.cm.Reds)   #to-do about corr
plt.show()

In [ ]:
#df=df.drop('Unnamed: 0.1',axis=1)
normalized_df.head()

In [ ]:
normalized_df=normalized_df.drop('Unnamed: 0', axis=1)
normalized_df=normalized_df.drop('Unnamed: 0.1.1', axis=1)

y=pd.DataFrame(y)

normalized_df.describe()

In [5]:
normalized_x=normalized_df.iloc[:,normalized_df.columns != 'Label']

normalized_x.describe()

Unnamed: 0.1.1.1   Source Port   Destination IP   Destination Port  \
count      1.245798e+06  1.245798e+06     1.245798e+06       1.245798e+06   
mean      -1.055835e-16 -1.849764e-16     6.128313e-16      -6.045583e-17   
std        1.000000e+00  1.000000e+00     1.000000e+00       1.000000e+00   
min       -9.858946e-01 -9.406960e-01    -7.380619e+00      -1.627133e+00   
25%       -7.561407e-01 -9.092742e-01     1.575856e-01      -8.716894e-01   
50%       -3.059936e-01 -5.546851e-01     1.575856e-01       1.857374e-03   
75%        3.562418e-01  1.002261e+00     1.575856e-01       8.720852e-01   
max        5.118678e+00  1.737069e+00     2.688699e+00       1.719132e+00   

           Protocol  Total Length of Fwd Packets   Fwd Packet Length Max  \
count  1.245798e+06                 1.245798e+06            1.245798e+06   
mean  -3.047958e-16                 8.568961e-17           -2.275931e-16   
std    1.000000e+00                 1.000000e+00            1.000000e+00   
min   -3.406373e+00                -7.420674e-01           -9.673956e-01   
25%    4.899846e-01                -4.243941e-01           -4.940017e-01   
50%    4.899846e-01                -3.994241e-01           -4.567917e-01   
75%    4.899846e-01                 2.275992e-01            3.313989e-02   
max    4.899846e-01                 1.438922e+02            6.526284e+00   

        Fwd Packet Length Min   Fwd Packet Length Mean  Bwd Packet Length Max  \
count            1.245798e+06             1.245798e+06           1.245798e+06   
mean            -8.742348e-17            -3.324465e-16          -6.159796e-19   
std              1.000000e+00             1.000000e+00           1.000000e+00   
min             -9.476172e-01            -9.575252e-01          -8.525948e-02   
25%             -4.720244e-01            -4.805696e-01          -8.525948e-02   
50%             -4.346415e-01            -4.430796e-01          -8.525948e-02   
75%              3.264403e-02             2.554496e-02          -8.525948e-02   
max              3.478096e+00             3.480870e+00           2.087880e+01   

       ...   URG Flag Count   CWE Flag Count   Average Packet Size  \
count  ...     1.245798e+06     1.245798e+06          1.245798e+06   
mean   ...     1.305306e-16    -1.257055e-17          4.343797e-17   
std    ...     1.000000e+00     1.000000e+00          1.000000e+00   
min    ...    -1.533709e-01    -1.014731e-01         -9.434708e-01   
25%    ...    -1.533709e-01    -1.014731e-01         -4.677879e-01   
50%    ...    -1.533709e-01    -1.014731e-01         -4.303980e-01   
75%    ...    -1.533709e-01    -1.014731e-01          3.697599e-02   
max    ...     6.520136e+00     9.854818e+00          2.114194e+00   

        Avg Fwd Segment Size   Avg Bwd Segment Size   Subflow Fwd Bytes  \
count           1.245798e+06           1.245798e+06        1.245798e+06   
mean           -3.324465e-16           1.952028e-17        8.568961e-17   
std             1.000000e+00           1.000000e+00        1.000000e+00   
min            -9.575252e-01          -9.547846e-02       -7.420674e-01   
25%            -4.805696e-01          -9.547846e-02       -4.243941e-01   
50%            -4.430796e-01          -9.547846e-02       -3.994241e-01   
75%             2.554496e-02          -9.547846e-02        2.275992e-01   
max             3.480870e+00           3.400920e+01        1.438922e+02   

       Init_Win_bytes_forward   Init_Win_bytes_backward      Idle Std  \
count            1.245798e+06              1.245798e+06  1.245798e+06   
mean             3.642036e-16             -7.246886e-17 -1.726568e-16   
std              1.000000e+00              1.000000e+00  1.000000e+00   
min             -3.622846e-01             -5.777066e-02 -1.627934e-01   
25%             -3.622846e-01             -5.777066e-02 -1.627934e-01   
50%             -3.622846e-01             -5.777066e-02 -1.627934e-01   
75%             -3.622846e-01             -5.777066e-02 -1.627934e-01   
max    

In [6]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(normalized_x, y, test_size=0.20, random_state=0)
y_train = np.array(y_train)

normalized_x.info()
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 35 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   Unnamed: 0.1.1.1             1245798 non-null  float64
 1    Source Port                 1245798 non-null  float64
 2    Destination IP              1245798 non-null  float64
 3    Destination Port            1245798 non-null  float64
 4    Protocol                    1245798 non-null  float64
 5   Total Length of Fwd Packets  1245798 non-null  float64
 6    Fwd Packet Length Max       1245798 non-null  float64
 7    Fwd Packet Length Min       1245798 non-null  float64
 8    Fwd Packet Length Mean      1245798 non-null  float64
 9   Bwd Packet Length Max        1245798 non-null  float64
 10   Bwd Packet Length Min       1245798 non-null  float64
 11   Bwd Packet Length Mean      1245798 non-null  float64
 12   Bwd Packet Length Std       1245798 non-n

In [7]:
#stochastic gradient descent
from  sklearn.linear_model import SGDClassifier, LinearRegression
from sklearn import metrics
lr = SGDClassifier(loss="log", penalty="l2", max_iter=200)
lr.fit(X_train, y_train)

C:\Users\jaswa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(loss='log', max_iter=200)

In [8]:
y_pred = lr.predict(X_test)
print("Stochastic Gradient Descent\nAccuracy =", metrics.accuracy_score(y_test, y_pred)*100)

Stochastic Gradient Descent
Accuracy = 81.36017017177717


In [9]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('Stochastic Gradient Descent')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Stochastic Gradient Descent
Accuracy =  81.36017017177717
Confusion Matrix =
 [[11389     8     1     1    42    57    12    10]
 [    0 25421     2     2 14321     0     3     0]
 [    0     0 39444   293    20     6     1     0]
 [    0    21   218 37753   880     1  1395     0]
 [   23 12792     0   105 24468    93    27     0]
 [    6     1     0     1     0 39666     1     0]
 [    3     0     0 15760    12     3 24473     0]
 [   20     0     0   231    13    16    42   103]]
Recall = 0.8136017017177717
Classification Report =
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     11520
           1       0.66      0.64      0.65     39749
           2       0.99      0.99      0.99     39764
           3       0.70      0.94      0.80     40268
           4       0.62      0.65      0.63     37508
           5       1.00      1.00      1.00     39675
           6       0.94      0.61      0.74     40251
           7       0.91    

In [10]:
yt = y_test.iloc[:,0]
yt=np.array(yt)

y_pred[3]

y_test = yt
#y_pred = y_pred[:, 0]

In [11]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

C:\Users\jaswa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=8)

In [12]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('K Nearest Neighbour Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

K Nearest Neighbour Classifier
Accuracy =  81.36017017177717
Confusion Matrix =
 [[11389     8     1     1    42    57    12    10]
 [    0 25421     2     2 14321     0     3     0]
 [    0     0 39444   293    20     6     1     0]
 [    0    21   218 37753   880     1  1395     0]
 [   23 12792     0   105 24468    93    27     0]
 [    6     1     0     1     0 39666     1     0]
 [    3     0     0 15760    12     3 24473     0]
 [   20     0     0   231    13    16    42   103]]
Recall = 0.8136017017177717
Classification Report =
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     11520
           1       0.66      0.64      0.65     39749
           2       0.99      0.99      0.99     39764
           3       0.70      0.94      0.80     40268
           4       0.62      0.65      0.63     37508
           5       1.00      1.00      1.00     39675
           6       0.94      0.61      0.74     40251
           7       0.91 

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

C:\Users\jaswa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [15]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Naive Bayes')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro')) 

Naive Bayes
Accuracy =  81.36017017177717
Confusion Matrix =
 [[11389     8     1     1    42    57    12    10]
 [    0 25421     2     2 14321     0     3     0]
 [    0     0 39444   293    20     6     1     0]
 [    0    21   218 37753   880     1  1395     0]
 [   23 12792     0   105 24468    93    27     0]
 [    6     1     0     1     0 39666     1     0]
 [    3     0     0 15760    12     3 24473     0]
 [   20     0     0   231    13    16    42   103]]
Recall = 0.8136017017177717
Classification Report =
               precision    recall  f1-score   support

           0       1.00      0.99      0.99     11520
           1       0.66      0.64      0.65     39749
           2       0.99      0.99      0.99     39764
           3       0.70      0.94      0.80     40268
           4       0.62      0.65      0.63     37508
           5       1.00      1.00      1.00     39675
           6       0.94      0.61      0.74     40251
           7       0.91      0.24      0.38